name = "gestbud-bff"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# KV namespace pour stocker les OTP (TTL 10 min)
# Créer avec : wrangler kv namespace create OTP_STORE
# Remplacer les id ci-dessous par les vrais IDs retournés
[[kv_namespaces]]
binding = "OTP_STORE"
id = "1c049ec5ba3047e9bd98e6e931e781ca"
preview_id = "53b9b865c317456787c1e535dc00ed95"

[env.dev]
name = "gestbud-bff-dev"
vars = {}

[[env.dev.kv_namespaces]]
binding = "OTP_STORE"
id = "516fdf60f2864832b85b748ec3cdc46f"
preview_id = "53b9b865c317456787c1e535dc00ed95"

[env.prod]
name = "gestbud-bff-prod"
workers_dev = true
preview_urls = false
vars = {}

[[env.prod.kv_namespaces]]
binding = "OTP_STORE"
id = "1c049ec5ba3047e9bd98e6e931e781ca"
